### ISSUE TITLE
Lab 1 Feedback

### ISSUE THREAD

**Issue by alanarnholt** [STT3851-Fall2019/lab1-ledbetterrm#1]
@ledbetterrm 

Lines 157 - 162 should use ref() and fig.cap ... replace with something like:

To display the saved file as shown in Figure `\@ref(fig:ig)`, use the `include_graphics()` function from `knitr`.^[Use the argument `dpi = 96` inside `include_graphics()`.] 

```{r, label = "ig", echo = FALSE, fig.cap = "Using `knitr::include_graphics()`"}
knitr::include_graphics("./JPG/YourFileName.jpeg", dpi = 96)
```

This will make the hyperlinks to the Figure work....and provide the footnote.

Lines 194-196 need a space after the numbers to format properly.

Review the Headers....a single hash gives chapter ## gives section inside chapter, etc...fix sections throughout.

For example, line 300 has `# 1.4 Loading Data`....should be `## Loading Data`

Line 544 needs three backticks at the start so the YAML displays properly.

The rest looks correct.

**Comment by ledbetterrm** [comment]
@alanarnholt Issues have been fixed.

**Comment by ledbetterrm** [comment]
@alanarnholt Issues have been fixed, again.

**Comment by alanarnholt** [comment]
@ledbetterrm looks good.  Closing issue
